sudo: required
services:
  - docker

language: groovy
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - docker-compose build
  # - docker-compose run --rm grails /grails/bin/grails test-app
  - docker-compose run --rm grails gradle test
