language: groovy

services:
  - postgresql

addons:
  hosts:
    - dbtest
# in Travis-CI: dbtest = localhost

before_script:
  - psql -c 'create database covers;' -U postgres

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  # - grails test dbm-update
  - gradle test integrationTest --info

env:
  - JDBC_TEST_DATABASE_URL=jdbc:postgresql://dbtest:5432/covers?user=postgres