language: groovy

services:
  - postgresql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - psql -c 'create database covers;' -U postgres
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  -
