version: '2'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: covers
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  dbtest:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: covers
      POSTGRES_PASSWORD: ""
  grails:
    # Grails 3.3.8 does not support Java 10. You will have to use Java 7 or Java 8 if you want to use Grails 3.3.8.
    image: gradle:3.5-jdk8
    environment:
      GRAILS_HOME: "/home/gradle/grails"
    volumes:
      - .:/home/gradle/covers
      - ./grails:/home/gradle/grails
      - ./cache:/home/gradle/.gradle
    ports:
      - "8080:8080"
    depends_on:
      - db
    working_dir: "/covers"
    command: "gradle bootRun"
  test:
    image: gradle:3.5-jdk8
    volumes:
      - .:/home/gradle/covers
      - ./cache:/home/gradle/.gradle
    ports:
      - "8080:8080"
    depends_on:
      - dbtest
    working_dir: "/home/gradle/covers"
    command: "gradle test integrationTest --info"
