version: '2'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: covers
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  dbtest:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: covers
      POSTGRES_PASSWORD: ""
  dev: &dev
    image: gradle:5.0-jdk11
    environment:
      GRAILS_HOME: "/home/gradle/grails"
      # PATH="$PATH:$GRAILS_HOME/bin" # ... won't work
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/gradle/grails/bin"
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/covers?user=postgres
    volumes:
      - .:/home/gradle/covers
      - ./grails:/home/gradle/grails
      - ./cache:/home/gradle/.gradle
    ports:
      - "8080:8080"
    depends_on:
      - db
    working_dir: "/home/gradle/covers"
    command: "gradle bootRun"
  test:
    <<: *dev
    depends_on:
      - dbtest
    command: "gradle test integrationTest --info"
    environment:
      JDBC_TEST_DATABASE_URL: jdbc:postgresql://dbtest:5432/covers?user=postgres
  prod:
    <<: *dev
    command: "gradle -Dgrails.env=prod bootRun"
